spring:
  datasource:
    url: jdbc:h2:mem:pricesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
  h2:
    console:
      enabled: true
      path: /h2-console
